//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailTextDB
    {
        public int ID { get; set; }
        public string Path { get; set; }
        public string Text { get; set; }
        public byte[] RTFText { get; set; }
        public System.DateTime ModifyTime { get; set; }
    }
}
