//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiskFile
    {
        public DiskFile()
        {
            this.FolderDBs = new HashSet<FolderDB>();
        }
    
        public int ID { get; set; }
        public string FilePath { get; set; }
        public Nullable<long> FileSize { get; set; }
        public byte[] FileContent { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    
        public virtual ICollection<FolderDB> FolderDBs { get; set; }
    }
}
